using System;
using System.Linq;
using System.Collections.Generic;

namespace MarubeniCreditWeb.Data.Package.RegionComunaPkg
{
    public class RegionComunaService
    {
        public List<Region> GetListRegiones()
        {
            List<Region> retorno = new List<Region>();

            try
            {

                retorno = new List<Region>()
                {
                new Region(){ idRegion = 1, region = "Región de Arica y Parinacota"},
                new Region(){ idRegion = 2, region = "Región de Tarapacá"},
                new Region(){ idRegion = 3, region = "Región de Antofagasta"},
                new Region(){ idRegion = 4, region = "Región de Atacama"},
                new Region(){ idRegion = 5, region = "Región de Coquimbo"},
                new Region(){ idRegion = 6, region = "Región de Valparaíso"},
                new Region(){ idRegion = 7, region = "Región del Libertador General Bernardo OHiggins"},
                new Region(){ idRegion = 8, region = "Región del Maule"},
                new Region(){ idRegion = 9, region = "Región de Ñuble"},
                new Region(){ idRegion = 10, region = "Región del Biobío"},
                new Region(){ idRegion = 11, region = "Región de La Araucanía"},
                new Region(){ idRegion = 12, region = "Región de Los Ríos"},
                new Region(){ idRegion = 13, region = "Región de Los Lagos"},
                new Region(){ idRegion = 14, region = "Región de Aysén del G. Carlos Ibáñez del Campo"},
                new Region(){ idRegion = 15, region = "Región de Magallanes y de la Antártica Chilena"},
                new Region(){ idRegion = 16, region = "Región Metropolitana de Santiago"}
                };
            }
            catch (Exception e)
            {
                throw new ArgumentException(e.Message);
            }

            return retorno;
        }

        public List<Comuna> GetListComunas(int idRegion = 0)
        {
            List<Comuna> retorno = new List<Comuna>();

            try
            {

                retorno = new List<Comuna>()
                {
                new Comuna(){ idComuna = 1, comuna = "Algarrobo", idRegion = 6},
                new Comuna(){ idComuna = 2, comuna = "Alhué", idRegion = 16},
                new Comuna(){ idComuna = 3, comuna = "Alto Biobío", idRegion = 10},
                new Comuna(){ idComuna = 4, comuna = "Alto del Carmen", idRegion = 4 },
                new Comuna(){ idComuna = 5, comuna = "Alto Hospicio", idRegion = 2},
                new Comuna(){ idComuna = 6, comuna = "Ancud", idRegion = 13},
                new Comuna(){ idComuna = 7, comuna = "Andacollo", idRegion = 5},
                new Comuna(){ idComuna = 8, comuna = "Angol", idRegion = 11},
                new Comuna(){ idComuna = 9, comuna = "Antártica", idRegion = 15},
                new Comuna(){ idComuna = 10, comuna = "Antofagasta", idRegion = 3},
                new Comuna(){ idComuna = 11, comuna = "Antuco", idRegion = 10},
                new Comuna(){ idComuna = 12, comuna = "Arauco", idRegion = 10},
                new Comuna(){ idComuna = 13, comuna = "Arica", idRegion = 1},
                new Comuna(){ idComuna = 14, comuna = "Aysén", idRegion = 14},
                new Comuna(){ idComuna = 15, comuna = "Buin", idRegion = 16},
                new Comuna(){ idComuna = 16, comuna = "Bulnes", idRegion = 9},
                new Comuna(){ idComuna = 17, comuna = "Cabildo", idRegion = 6},
                new Comuna(){ idComuna = 18, comuna = "Cabo de Hornos", idRegion = 15},
                new Comuna(){ idComuna = 19, comuna = "Cabrero", idRegion = 10},
                new Comuna(){ idComuna = 20, comuna = "Calama", idRegion = 3},
                new Comuna(){ idComuna = 21, comuna = "Calbuco", idRegion = 13},
                new Comuna(){ idComuna = 22, comuna = "Caldera", idRegion = 4},
                new Comuna(){ idComuna = 23, comuna = "Calera de Tango", idRegion = 16},
                new Comuna(){ idComuna = 24, comuna = "Calle Larga", idRegion = 6},
                new Comuna(){ idComuna = 25, comuna = "Camarones", idRegion = 1},
                new Comuna(){ idComuna = 26, comuna = "Camiña", idRegion = 2},
                new Comuna(){ idComuna = 27, comuna = "Canela", idRegion = 5},
                new Comuna(){ idComuna = 28, comuna = "Cañete", idRegion = 10},
                new Comuna(){ idComuna = 29, comuna = "Carahue", idRegion = 11},
                new Comuna(){ idComuna = 30, comuna = "Cartagena", idRegion = 6},
                new Comuna(){ idComuna = 31, comuna = "Casablanca", idRegion = 6},
                new Comuna(){ idComuna = 32, comuna = "Castro", idRegion = 13},
                new Comuna(){ idComuna = 33, comuna = "Catemu", idRegion = 6},
                new Comuna(){ idComuna = 34, comuna = "Cauquenes", idRegion = 8},
                new Comuna(){ idComuna = 35, comuna = "Cerrillos", idRegion = 16},
                new Comuna(){ idComuna = 36, comuna = "Cerro Navia", idRegion = 16},
                new Comuna(){ idComuna = 37, comuna = "Chaitén", idRegion = 13},
                new Comuna(){ idComuna = 38, comuna = "Chanco", idRegion = 8},
                new Comuna(){ idComuna = 39, comuna = "Chañaral", idRegion = 4},
                new Comuna(){ idComuna = 40, comuna = "Chépica", idRegion = 7},
                new Comuna(){ idComuna = 41, comuna = "Chiguayante", idRegion = 10},
                new Comuna(){ idComuna = 42, comuna = "Chile Chico", idRegion = 14},
                new Comuna(){ idComuna = 43, comuna = "Chillán", idRegion = 9},
                new Comuna(){ idComuna = 44, comuna = "Chillán Viejo", idRegion = 9},
                new Comuna(){ idComuna = 45, comuna = "Chimbarongo", idRegion = 7},
                new Comuna(){ idComuna = 46, comuna = "Cholchol", idRegion = 11},
                new Comuna(){ idComuna = 47, comuna = "Chonchi", idRegion = 13},
                new Comuna(){ idComuna = 48, comuna = "Cisnes", idRegion = 14},
                new Comuna(){ idComuna = 49, comuna = "Cobquecura", idRegion = 9},
                new Comuna(){ idComuna = 50, comuna = "Cochamó", idRegion = 13},
                new Comuna(){ idComuna = 51, comuna = "Cochrane", idRegion = 14},
                new Comuna(){ idComuna = 52, comuna = "Codegua", idRegion = 7},
                new Comuna(){ idComuna = 53, comuna = "Coelemu", idRegion = 9},
                new Comuna(){ idComuna = 54, comuna = "Coihueco", idRegion = 9},
                new Comuna(){ idComuna = 55, comuna = "Coinco", idRegion = 7},
                new Comuna(){ idComuna = 56, comuna = "Colbún", idRegion = 8},
                new Comuna(){ idComuna = 57, comuna = "Colchane", idRegion = 2},
                new Comuna(){ idComuna = 58, comuna = "Colina", idRegion = 16},
                new Comuna(){ idComuna = 59, comuna = "Collipulli", idRegion = 11},
                new Comuna(){ idComuna = 60, comuna = "Coltauco", idRegion = 7},
                new Comuna(){ idComuna = 61, comuna = "Combarbalá", idRegion = 5},
                new Comuna(){ idComuna = 62, comuna = "Concepción", idRegion = 10},
                new Comuna(){ idComuna = 63, comuna = "Conchalí", idRegion = 16},
                new Comuna(){ idComuna = 64, comuna = "Concón", idRegion = 6},
                new Comuna(){ idComuna = 65, comuna = "Constitución", idRegion = 8},
                new Comuna(){ idComuna = 66, comuna = "Contulmo", idRegion = 10},
                new Comuna(){ idComuna = 67, comuna = "Copiapó", idRegion = 4},
                new Comuna(){ idComuna = 68, comuna = "Coquimbo", idRegion = 5},
                new Comuna(){ idComuna = 69, comuna = "Coronel", idRegion = 10},
                new Comuna(){ idComuna = 70, comuna = "Corral", idRegion = 12},
                new Comuna(){ idComuna = 71, comuna = "Coyhaique", idRegion = 14},
                new Comuna(){ idComuna = 72, comuna = "Cunco", idRegion = 11},
                new Comuna(){ idComuna = 73, comuna = "Curacautín", idRegion = 11},
                new Comuna(){ idComuna = 74, comuna = "Curacaví", idRegion = 16},
                new Comuna(){ idComuna = 75, comuna = "Curaco de Vélez", idRegion = 13},
                new Comuna(){ idComuna = 76, comuna = "Curanilahue", idRegion = 10},
                new Comuna(){ idComuna = 77, comuna = "Curarrehue", idRegion = 11},
                new Comuna(){ idComuna = 78, comuna = "Curepto", idRegion = 8},
                new Comuna(){ idComuna = 79, comuna = "Curicó", idRegion = 8},
                new Comuna(){ idComuna = 80, comuna = "Dalcahue", idRegion = 13},
                new Comuna(){ idComuna = 81, comuna = "Diego de Almagro", idRegion = 4},
                new Comuna(){ idComuna = 82, comuna = "Doñihue", idRegion = 7},
                new Comuna(){ idComuna = 83, comuna = "El Bosque", idRegion = 16},
                new Comuna(){ idComuna = 84, comuna = "El Carmen", idRegion = 9},
                new Comuna(){ idComuna = 85, comuna = "El Monte", idRegion = 16},
                new Comuna(){ idComuna = 86, comuna = "El Quisco", idRegion = 6},
                new Comuna(){ idComuna = 87, comuna = "El Tabo", idRegion = 6},
                new Comuna(){ idComuna = 88, comuna = "Empedrado", idRegion = 8},
                new Comuna(){ idComuna = 89, comuna = "Ercilla", idRegion = 11},
                new Comuna(){ idComuna = 90, comuna = "Estación Central", idRegion = 16},
                new Comuna(){ idComuna = 91, comuna = "Florida", idRegion = 10},
                new Comuna(){ idComuna = 92, comuna = "Freire", idRegion = 11},
                new Comuna(){ idComuna = 93, comuna = "Freirina", idRegion = 4},
                new Comuna(){ idComuna = 94, comuna = "Fresia", idRegion = 13},
                new Comuna(){ idComuna = 95, comuna = "Frutillar", idRegion = 13},
                new Comuna(){ idComuna = 96, comuna = "Futaleufú", idRegion = 13},
                new Comuna(){ idComuna = 97, comuna = "Futrono", idRegion = 12},
                new Comuna(){ idComuna = 98, comuna = "Galvarino", idRegion = 11},
                new Comuna(){ idComuna = 99, comuna = "General Lagos", idRegion = 1},
                new Comuna(){ idComuna = 100, comuna = "Gorbea", idRegion = 11},
                new Comuna(){ idComuna = 101, comuna = "Graneros", idRegion = 7},
                new Comuna(){ idComuna = 102, comuna = "Guaitecas", idRegion = 14},
                new Comuna(){ idComuna = 103, comuna = "Hijuelas", idRegion = 6},
                new Comuna(){ idComuna = 104, comuna = "Hualaihué", idRegion = 13},
                new Comuna(){ idComuna = 105, comuna = "Hualañé", idRegion = 8},
                new Comuna(){ idComuna = 106, comuna = "Hualpén", idRegion = 10},
                new Comuna(){ idComuna = 107, comuna = "Hualqui", idRegion = 10},
                new Comuna(){ idComuna = 108, comuna = "Huara", idRegion = 2},
                new Comuna(){ idComuna = 109, comuna = "Huasco", idRegion = 4},
                new Comuna(){ idComuna = 110, comuna = "Huechuraba", idRegion = 16},
                new Comuna(){ idComuna = 111, comuna = "Illapel", idRegion = 5},
                new Comuna(){ idComuna = 112, comuna = "Independencia", idRegion = 16},
                new Comuna(){ idComuna = 113, comuna = "Iquique", idRegion = 2},
                new Comuna(){ idComuna = 114, comuna = "Isla de Maipo", idRegion = 16},
                new Comuna(){ idComuna = 115, comuna = "Isla de Pascua", idRegion = 6},
                new Comuna(){ idComuna = 116, comuna = "Juan Fernández", idRegion = 6},
                new Comuna(){ idComuna = 117, comuna = "La Calera", idRegion = 6},
                new Comuna(){ idComuna = 118, comuna = "La Cisterna", idRegion = 16},
                new Comuna(){ idComuna = 119, comuna = "La Cruz", idRegion = 6},
                new Comuna(){ idComuna = 120, comuna = "La Estrella", idRegion = 7},
                new Comuna(){ idComuna = 121, comuna = "La Florida", idRegion = 16},
                new Comuna(){ idComuna = 122, comuna = "La Granja", idRegion = 16},
                new Comuna(){ idComuna = 123, comuna = "La Higuera", idRegion = 5},
                new Comuna(){ idComuna = 124, comuna = "La Ligua", idRegion = 6},
                new Comuna(){ idComuna = 125, comuna = "La Pintana", idRegion = 16},
                new Comuna(){ idComuna = 126, comuna = "La Reina", idRegion = 16},
                new Comuna(){ idComuna = 127, comuna = "La Serena", idRegion = 5},
                new Comuna(){ idComuna = 128, comuna = "La Unión", idRegion = 12},
                new Comuna(){ idComuna = 129, comuna = "Lago Ranco", idRegion = 12},
                new Comuna(){ idComuna = 130, comuna = "Lago Verde", idRegion = 14},
                new Comuna(){ idComuna = 131, comuna = "Laguna Blanca", idRegion = 15},
                new Comuna(){ idComuna = 132, comuna = "Laja", idRegion = 10},
                new Comuna(){ idComuna = 133, comuna = "Lampa", idRegion = 16},
                new Comuna(){ idComuna = 134, comuna = "Lanco", idRegion = 12},
                new Comuna(){ idComuna = 135, comuna = "Las Cabras", idRegion = 7},
                new Comuna(){ idComuna = 136, comuna = "Las Condes", idRegion = 16},
                new Comuna(){ idComuna = 137, comuna = "Lautaro", idRegion = 11},
                new Comuna(){ idComuna = 138, comuna = "Lebu", idRegion = 10},
                new Comuna(){ idComuna = 139, comuna = "Licantén", idRegion = 8},
                new Comuna(){ idComuna = 140, comuna = "Limache", idRegion = 6},
                new Comuna(){ idComuna = 141, comuna = "Linares", idRegion = 8},
                new Comuna(){ idComuna = 142, comuna = "Litueche", idRegion = 7},
                new Comuna(){ idComuna = 143, comuna = "Llaillay", idRegion = 6},
                new Comuna(){ idComuna = 144, comuna = "Llanquihue", idRegion = 13},
                new Comuna(){ idComuna = 145, comuna = "Lo Barnechea", idRegion = 16},
                new Comuna(){ idComuna = 146, comuna = "Lo Espejo", idRegion = 16},
                new Comuna(){ idComuna = 147, comuna = "Lo Prado", idRegion = 16},
                new Comuna(){ idComuna = 148, comuna = "Lolol", idRegion = 7},
                new Comuna(){ idComuna = 149, comuna = "Loncoche", idRegion = 11},
                new Comuna(){ idComuna = 150, comuna = "Longaví", idRegion = 8},
                new Comuna(){ idComuna = 151, comuna = "Lonquimay", idRegion = 11},
                new Comuna(){ idComuna = 152, comuna = "Los Álamos", idRegion = 10},
                new Comuna(){ idComuna = 153, comuna = "Los Andes", idRegion = 6},
                new Comuna(){ idComuna = 154, comuna = "Los Ángeles", idRegion = 10},
                new Comuna(){ idComuna = 155, comuna = "Los Lagos", idRegion = 12},
                new Comuna(){ idComuna = 156, comuna = "Los Muermos", idRegion = 13},
                new Comuna(){ idComuna = 157, comuna = "Los Sauces", idRegion = 11},
                new Comuna(){ idComuna = 158, comuna = "Los Vilos", idRegion = 5},
                new Comuna(){ idComuna = 159, comuna = "Lota", idRegion = 10},
                new Comuna(){ idComuna = 160, comuna = "Lumaco", idRegion = 11},
                new Comuna(){ idComuna = 161, comuna = "Machalí", idRegion = 7},
                new Comuna(){ idComuna = 162, comuna = "Macul", idRegion = 16},
                new Comuna(){ idComuna = 163, comuna = "Máfil", idRegion = 12},
                new Comuna(){ idComuna = 164, comuna = "Maipú", idRegion = 16},
                new Comuna(){ idComuna = 165, comuna = "Malloa", idRegion = 7},
                new Comuna(){ idComuna = 166, comuna = "Marchihue", idRegion = 7},
                new Comuna(){ idComuna = 167, comuna = "María Elena", idRegion = 3},
                new Comuna(){ idComuna = 168, comuna = "María Pinto", idRegion = 16},
                new Comuna(){ idComuna = 169, comuna = "Mariquina", idRegion = 12},
                new Comuna(){ idComuna = 170, comuna = "Maule", idRegion = 8},
                new Comuna(){ idComuna = 171, comuna = "Maullín", idRegion = 13},
                new Comuna(){ idComuna = 172, comuna = "Mejillones", idRegion = 3},
                new Comuna(){ idComuna = 173, comuna = "Melipeuco", idRegion = 11},
                new Comuna(){ idComuna = 174, comuna = "Melipilla", idRegion = 16},
                new Comuna(){ idComuna = 175, comuna = "Molina", idRegion = 8},
                new Comuna(){ idComuna = 176, comuna = "Monte Patria", idRegion = 5},
                new Comuna(){ idComuna = 177, comuna = "Mostazal", idRegion = 7},
                new Comuna(){ idComuna = 178, comuna = "Mulchén", idRegion = 10},
                new Comuna(){ idComuna = 179, comuna = "Nacimiento", idRegion = 10},
                new Comuna(){ idComuna = 180, comuna = "Nancagua", idRegion = 7},
                new Comuna(){ idComuna = 181, comuna = "Natales", idRegion = 15},
                new Comuna(){ idComuna = 182, comuna = "Navidad", idRegion = 7},
                new Comuna(){ idComuna = 183, comuna = "Negrete", idRegion = 10},
                new Comuna(){ idComuna = 184, comuna = "Ninhue", idRegion = 9},
                new Comuna(){ idComuna = 185, comuna = "Nogales", idRegion = 6},
                new Comuna(){ idComuna = 186, comuna = "Nueva Imperial", idRegion = 11},
                new Comuna(){ idComuna = 187, comuna = "Ñiquén", idRegion = 9},
                new Comuna(){ idComuna = 188, comuna = "Ñuñoa", idRegion = 16},
                new Comuna(){ idComuna = 189, comuna = "OHiggins", idRegion = 14},
                new Comuna(){ idComuna = 190, comuna = "Olivar", idRegion = 7},
                new Comuna(){ idComuna = 191, comuna = "Ollagüe", idRegion = 3},
                new Comuna(){ idComuna = 192, comuna = "Olmué", idRegion = 6},
                new Comuna(){ idComuna = 193, comuna = "Osorno", idRegion = 13},
                new Comuna(){ idComuna = 194, comuna = "Ovalle", idRegion = 5},
                new Comuna(){ idComuna = 195, comuna = "Padre Hurtado", idRegion = 16},
                new Comuna(){ idComuna = 196, comuna = "Padre Las Casas", idRegion = 11},
                new Comuna(){ idComuna = 197, comuna = "Paihuano", idRegion = 5},
                new Comuna(){ idComuna = 198, comuna = "Paillaco", idRegion = 12},
                new Comuna(){ idComuna = 199, comuna = "Paine", idRegion = 16},
                new Comuna(){ idComuna = 200, comuna = "Palena", idRegion = 13},
                new Comuna(){ idComuna = 201, comuna = "Palmilla", idRegion = 7},
                new Comuna(){ idComuna = 202, comuna = "Panguipulli", idRegion = 12},
                new Comuna(){ idComuna = 203, comuna = "Panquehue", idRegion = 6},
                new Comuna(){ idComuna = 204, comuna = "Papudo", idRegion = 6},
                new Comuna(){ idComuna = 205, comuna = "Paredones", idRegion = 7},
                new Comuna(){ idComuna = 206, comuna = "Parral", idRegion = 8},
                new Comuna(){ idComuna = 207, comuna = "Pedro Aguirre Cerda", idRegion = 16},
                new Comuna(){ idComuna = 208, comuna = "Pelarco", idRegion = 8},
                new Comuna(){ idComuna = 209, comuna = "Pelluhue", idRegion = 8},
                new Comuna(){ idComuna = 210, comuna = "Pemuco", idRegion = 9},
                new Comuna(){ idComuna = 211, comuna = "Pencahue", idRegion = 8},
                new Comuna(){ idComuna = 212, comuna = "Penco", idRegion = 10},
                new Comuna(){ idComuna = 213, comuna = "Peñaflor", idRegion = 16},
                new Comuna(){ idComuna = 214, comuna = "Peñalolén", idRegion = 16},
                new Comuna(){ idComuna = 215, comuna = "Peralillo", idRegion = 7},
                new Comuna(){ idComuna = 216, comuna = "Perquenco", idRegion = 11},
                new Comuna(){ idComuna = 217, comuna = "Petorca", idRegion = 6},
                new Comuna(){ idComuna = 218, comuna = "Peumo", idRegion = 7},
                new Comuna(){ idComuna = 219, comuna = "Pica", idRegion = 2},
                new Comuna(){ idComuna = 220, comuna = "Pichidegua", idRegion = 7},
                new Comuna(){ idComuna = 221, comuna = "Pichilemu", idRegion = 7},
                new Comuna(){ idComuna = 222, comuna = "Pinto", idRegion = 9},
                new Comuna(){ idComuna = 223, comuna = "Pirque", idRegion = 16},
                new Comuna(){ idComuna = 224, comuna = "Pitrufquén", idRegion = 11},
                new Comuna(){ idComuna = 225, comuna = "Placilla", idRegion = 7},
                new Comuna(){ idComuna = 226, comuna = "Portezuelo", idRegion = 9},
                new Comuna(){ idComuna = 227, comuna = "Porvenir", idRegion = 15},
                new Comuna(){ idComuna = 228, comuna = "Pozo Almonte", idRegion = 2},
                new Comuna(){ idComuna = 229, comuna = "Primavera", idRegion = 15},
                new Comuna(){ idComuna = 230, comuna = "Providencia", idRegion = 16},
                new Comuna(){ idComuna = 231, comuna = "Puchuncaví", idRegion = 6},
                new Comuna(){ idComuna = 232, comuna = "Pucón", idRegion = 11},
                new Comuna(){ idComuna = 233, comuna = "Pudahuel", idRegion = 16},
                new Comuna(){ idComuna = 234, comuna = "Puente Alto"},
                new Comuna(){ idComuna = 235, comuna = "Puerto Montt", idRegion = 13},
                new Comuna(){ idComuna = 236, comuna = "Puerto Octay", idRegion = 13},
                new Comuna(){ idComuna = 237, comuna = "Puerto Varas", idRegion = 13},
                new Comuna(){ idComuna = 238, comuna = "Pumanque", idRegion = 7},
                new Comuna(){ idComuna = 239, comuna = "Punitaqui", idRegion = 5},
                new Comuna(){ idComuna = 240, comuna = "Punta Arenas", idRegion = 15},
                new Comuna(){ idComuna = 241, comuna = "Puqueldón", idRegion = 13},
                new Comuna(){ idComuna = 242, comuna = "Purén", idRegion = 11},
                new Comuna(){ idComuna = 243, comuna = "Purranque", idRegion = 13},
                new Comuna(){ idComuna = 244, comuna = "Putaendo", idRegion = 6},
                new Comuna(){ idComuna = 245, comuna = "Putre", idRegion = 1},
                new Comuna(){ idComuna = 246, comuna = "Puyehue", idRegion = 13},
                new Comuna(){ idComuna = 247, comuna = "Queilén", idRegion = 13},
                new Comuna(){ idComuna = 248, comuna = "Quellón", idRegion = 13},
                new Comuna(){ idComuna = 249, comuna = "Quemchi", idRegion = 13},
                new Comuna(){ idComuna = 250, comuna = "Quilaco", idRegion = 10},
                new Comuna(){ idComuna = 251, comuna = "Quilicura", idRegion = 16},
                new Comuna(){ idComuna = 252, comuna = "Quilleco", idRegion = 10},
                new Comuna(){ idComuna = 253, comuna = "Quillón", idRegion = 9},
                new Comuna(){ idComuna = 254, comuna = "Quillota", idRegion = 6},
                new Comuna(){ idComuna = 255, comuna = "Quilpué", idRegion = 6},
                new Comuna(){ idComuna = 256, comuna = "Quinchao", idRegion = 13},
                new Comuna(){ idComuna = 257, comuna = "Quinta de Tilcoco", idRegion = 7},
                new Comuna(){ idComuna = 258, comuna = "Quinta Normal", idRegion = 16},
                new Comuna(){ idComuna = 259, comuna = "Quintero", idRegion = 6},
                new Comuna(){ idComuna = 260, comuna = "Quirihue", idRegion = 9},
                new Comuna(){ idComuna = 261, comuna = "Rancagua", idRegion = 7},
                new Comuna(){ idComuna = 262, comuna = "Ránquil", idRegion = 9},
                new Comuna(){ idComuna = 263, comuna = "Rauco", idRegion = 8},
                new Comuna(){ idComuna = 264, comuna = "Recoleta", idRegion = 16},
                new Comuna(){ idComuna = 265, comuna = "Renaico", idRegion = 11},
                new Comuna(){ idComuna = 266, comuna = "Renca", idRegion = 16},
                new Comuna(){ idComuna = 267, comuna = "Rengo", idRegion = 7},
                new Comuna(){ idComuna = 268, comuna = "Requínoa", idRegion = 7},
                new Comuna(){ idComuna = 269, comuna = "Retiro", idRegion = 8},
                new Comuna(){ idComuna = 270, comuna = "Rinconada", idRegion = 6},
                new Comuna(){ idComuna = 271, comuna = "Río Bueno", idRegion = 12},
                new Comuna(){ idComuna = 272, comuna = "Río Claro", idRegion = 8},
                new Comuna(){ idComuna = 273, comuna = "Río Hurtado", idRegion = 5},
                new Comuna(){ idComuna = 274, comuna = "Río Ibáñez", idRegion = 14},
                new Comuna(){ idComuna = 275, comuna = "Río Negro", idRegion = 13},
                new Comuna(){ idComuna = 276, comuna = "Río Verde", idRegion = 15},
                new Comuna(){ idComuna = 277, comuna = "Romeral", idRegion = 8},
                new Comuna(){ idComuna = 278, comuna = "Saavedra", idRegion = 11},
                new Comuna(){ idComuna = 279, comuna = "Sagrada Familia", idRegion = 8},
                new Comuna(){ idComuna = 280, comuna = "Salamanca", idRegion = 5},
                new Comuna(){ idComuna = 281, comuna = "San Antonio", idRegion = 6},
                new Comuna(){ idComuna = 282, comuna = "San Bernardo", idRegion = 16},
                new Comuna(){ idComuna = 283, comuna = "San Carlos", idRegion = 9},
                new Comuna(){ idComuna = 284, comuna = "San Clemente", idRegion = 8},
                new Comuna(){ idComuna = 285, comuna = "San Esteban", idRegion = 6},
                new Comuna(){ idComuna = 286, comuna = "San Fabián", idRegion = 9},
                new Comuna(){ idComuna = 287, comuna = "San Felipe", idRegion = 6},
                new Comuna(){ idComuna = 288, comuna = "San Fernando", idRegion = 7},
                new Comuna(){ idComuna = 289, comuna = "San Gregorio", idRegion = 15},
                new Comuna(){ idComuna = 290, comuna = "San Ignacio", idRegion = 9},
                new Comuna(){ idComuna = 291, comuna = "San Javier", idRegion = 8},
                new Comuna(){ idComuna = 292, comuna = "San Joaquín", idRegion = 16},
                new Comuna(){ idComuna = 293, comuna = "San José de Maipo", idRegion = 16},
                new Comuna(){ idComuna = 294, comuna = "San Juan de la Costa", idRegion = 13},
                new Comuna(){ idComuna = 295, comuna = "San Miguel", idRegion = 16},
                new Comuna(){ idComuna = 296, comuna = "San Nicolás", idRegion = 9},
                new Comuna(){ idComuna = 297, comuna = "San Pablo", idRegion = 13},
                new Comuna(){ idComuna = 298, comuna = "San Pedro", idRegion = 16},
                new Comuna(){ idComuna = 299, comuna = "San Pedro de Atacama", idRegion = 3},
                new Comuna(){ idComuna = 300, comuna = "San Pedro de la Paz", idRegion = 10},
                new Comuna(){ idComuna = 301, comuna = "San Rafael", idRegion = 8},
                new Comuna(){ idComuna = 302, comuna = "San Ramón", idRegion = 16},
                new Comuna(){ idComuna = 303, comuna = "San Rosendo", idRegion = 10},
                new Comuna(){ idComuna = 304, comuna = "San Vicente", idRegion = 7},
                new Comuna(){ idComuna = 305, comuna = "Santa Bárbara", idRegion = 10},
                new Comuna(){ idComuna = 306, comuna = "Santa Cruz", idRegion = 7},
                new Comuna(){ idComuna = 307, comuna = "Santa Juana", idRegion = 10},
                new Comuna(){ idComuna = 308, comuna = "Santa María", idRegion = 6},
                new Comuna(){ idComuna = 309, comuna = "Santiago", idRegion = 16},
                new Comuna(){ idComuna = 310, comuna = "Santo Domingo", idRegion = 6},
                new Comuna(){ idComuna = 311, comuna = "Sierra Gorda", idRegion = 3},
                new Comuna(){ idComuna = 312, comuna = "Talagante", idRegion = 16},
                new Comuna(){ idComuna = 313, comuna = "Talca", idRegion = 8},
                new Comuna(){ idComuna = 314, comuna = "Talcahuano", idRegion = 10},
                new Comuna(){ idComuna = 315, comuna = "Taltal", idRegion = 3},
                new Comuna(){ idComuna = 316, comuna = "Temuco", idRegion = 11},
                new Comuna(){ idComuna = 317, comuna = "Teno", idRegion = 8},
                new Comuna(){ idComuna = 318, comuna = "Teodoro Schmidt", idRegion = 11},
                new Comuna(){ idComuna = 319, comuna = "Tierra Amarilla", idRegion = 4},
                new Comuna(){ idComuna = 320, comuna = "Tiltil", idRegion = 16},
                new Comuna(){ idComuna = 321, comuna = "Timaukel", idRegion = 15},
                new Comuna(){ idComuna = 322, comuna = "Tirúa", idRegion = 10},
                new Comuna(){ idComuna = 323, comuna = "Tocopilla", idRegion = 3},
                new Comuna(){ idComuna = 324, comuna = "Toltén", idRegion = 11},
                new Comuna(){ idComuna = 325, comuna = "Tomé", idRegion = 10},
                new Comuna(){ idComuna = 326, comuna = "Torres del Paine", idRegion = 15},
                new Comuna(){ idComuna = 327, comuna = "Tortel", idRegion = 14},
                new Comuna(){ idComuna = 328, comuna = "Traiguén", idRegion = 11},
                new Comuna(){ idComuna = 329, comuna = "Treguaco", idRegion = 9},
                new Comuna(){ idComuna = 330, comuna = "Tucapel", idRegion = 10},
                new Comuna(){ idComuna = 331, comuna = "Valdivia", idRegion = 12},
                new Comuna(){ idComuna = 332, comuna = "Vallenar", idRegion = 4},
                new Comuna(){ idComuna = 333, comuna = "Valparaíso", idRegion = 6},
                new Comuna(){ idComuna = 334, comuna = "Vichuquén", idRegion = 8},
                new Comuna(){ idComuna = 335, comuna = "Victoria", idRegion = 11},
                new Comuna(){ idComuna = 336, comuna = "Vicuña", idRegion = 5},
                new Comuna(){ idComuna = 337, comuna = "Vilcún", idRegion = 11},
                new Comuna(){ idComuna = 338, comuna = "Villa Alegre", idRegion = 8},
                new Comuna(){ idComuna = 339, comuna = "Villa Alemana", idRegion = 6},
                new Comuna(){ idComuna = 340, comuna = "Villarrica", idRegion = 11},
                new Comuna(){ idComuna = 341, comuna = "Viña del Mar", idRegion = 6},
                new Comuna(){ idComuna = 342, comuna = "Vitacura", idRegion = 16},
                new Comuna(){ idComuna = 343, comuna = "Yerbas Buenas", idRegion = 8},
                new Comuna(){ idComuna = 344, comuna = "Yumbel", idRegion = 10},
                new Comuna(){ idComuna = 345, comuna = "Yungay", idRegion = 9},
                new Comuna(){ idComuna = 346, comuna = "Zapallar", idRegion = 6},

                };

                
            }
            catch (Exception e)
            {
                throw new ArgumentException(e.Message);
            }
            if (idRegion != 0)
            {
                return retorno.Where(x => x.idRegion == idRegion).ToList();
            }
            else
            {
                return retorno;
            }
        }

    }
}
